- name: Deploy Spring Boot with MongoDB on Azure VM
  hosts: localhost
  become: yes 

  tasks:
    - name: Update apt cache and install Docker
      apt:
        update_cache: yes
        name: docker.io
      become: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Create Network
      ansible.builtin.docker_network:
        name: spring_mongo_network

    - name: Pull MongoDB Image
      ansible.builtin.docker_image:
        name: mongo
        source: pull

    - name: Create MongoDB Container
      ansible.builtin.docker_container:
        name: mongodb
        image: mongo
        ports:
          - "27017:27017"
        networks:
          - name: spring_mongo_network
        volumes:
          - 'data:/data/db'
        state: started
    
    - name: Pull SpringBoot Image
      ansible.builtin.docker_image:
        name: mazenissaoui2000/ob-item
        source: pull

    - name: Create SpringBoot container
      ansible.builtin.docker_container:
        name: springboot
        image: mazenissaoui2000/ob-item
        ports:
          - "8081:8081"
        networks:
          - name: spring_mongo_network
        state: started

